services:
    profile:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: profile

        env_file:
            - .env
        ports:
            - "${PORT_PROFILE}:${PORT_PROFILE}"

        volumes:
            - ./static:/app/static
        networks:
            - project_network

        restart: always
networks:
  project_network:
    external: true
